server:
  name: go-message
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb://@localhost:27017
  database: master_data

kafka_consumer:
  brokers: tricycle-01.srvs.cloudkafka.com:9094
  client:
    tls_enable: true
    sasl_enable: true
    sasl_handshake: true
    tls:
      insecure_skip_verify: true
    username: ah1t9hk0
    password: QvMB75cxJ48KYRnGfwXcRNxzALyAeb7-
  group_id: my-group
  topic: ah1t9hk0-default

retry:
  1: 5
  2: 7
  3: 9
